import type { Category, Listing, BlacklistEntry } from '../types';

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-01', slug: 'housing',    name_uk: 'Нерухомість',        name_ro: 'Imobiliare',          name_en: 'Real Estate',         icon: 'Home' },
  { id: 'cat-02', slug: 'transport',  name_uk: 'Перевезення',         name_ro: 'Transport',           name_en: 'Transportation',      icon: 'Car' },
  { id: 'cat-03', slug: 'beauty',     name_uk: "Краса та здоров'я",  name_ro: 'Frumusete',           name_en: 'Beauty & Health',     icon: 'Sparkles' },
  { id: 'cat-04', slug: 'medicine',   name_uk: 'Медицина',            name_ro: 'Medicina',            name_en: 'Medicine',            icon: 'Heart' },
  { id: 'cat-05', slug: 'veterinary', name_uk: 'Ветеринарія',         name_ro: 'Veterinar',           name_en: 'Veterinary',          icon: 'Dog' },
  { id: 'cat-06', slug: 'restaurants',name_uk: 'Ресторани і кафе',    name_ro: 'Restaurante',         name_en: 'Restaurants & Cafes', icon: 'UtensilsCrossed' },
  { id: 'cat-07', slug: 'repair',     name_uk: 'Ремонт і будівництво',name_ro: 'Reparatii',           name_en: 'Repair & Construction',icon: 'Wrench' },
  { id: 'cat-08', slug: 'cleaning',   name_uk: 'Клінінг',             name_ro: 'Curatenie',           name_en: 'Cleaning',            icon: 'SprayCan' },
  { id: 'cat-09', slug: 'education',  name_uk: 'Освіта та курси',     name_ro: 'Educatie',            name_en: 'Education & Courses', icon: 'GraduationCap' },
  { id: 'cat-10', slug: 'legal',      name_uk: 'Юридичні послуги',    name_ro: 'Juridice',            name_en: 'Legal Services',      icon: 'Scale' },
  { id: 'cat-11', slug: 'accounting', name_uk: 'Бухгалтерія',         name_ro: 'Contabilitate',       name_en: 'Accounting',          icon: 'Calculator' },
  { id: 'cat-12', slug: 'childcare',  name_uk: 'Дитячі послуги',      name_ro: 'Copii',               name_en: 'Childcare',           icon: 'Baby' },
  { id: 'cat-13', slug: 'photo_video',name_uk: 'Фото та відео',       name_ro: 'Foto/Video',          name_en: 'Photo & Video',       icon: 'Camera' },
  { id: 'cat-14', slug: 'it_services',name_uk: 'IT послуги',          name_ro: 'IT',                  name_en: 'IT Services',         icon: 'Monitor' },
  { id: 'cat-15', slug: 'auto',       name_uk: 'Автосервіс',          name_ro: 'Auto',                name_en: 'Auto Service',        icon: 'CarFront' },
  { id: 'cat-16', slug: 'delivery',   name_uk: 'Доставка',            name_ro: 'Livrare',             name_en: 'Delivery',            icon: 'Package' },
  { id: 'cat-17', slug: 'events',     name_uk: 'Івенти',              name_ro: 'Evenimente',          name_en: 'Events',              icon: 'PartyPopper' },
  { id: 'cat-18', slug: 'pets',       name_uk: 'Тварини',             name_ro: 'Animale',             name_en: 'Pets',                icon: 'PawPrint' },
  { id: 'cat-19', slug: 'marketplace',name_uk: 'Купівля / Продаж',    name_ro: 'Cumparare/Vanzare',   name_en: 'Buy / Sell',          icon: 'ShoppingBag' },
  { id: 'cat-20', slug: 'other',      name_uk: 'Інше',                name_ro: 'Altele',              name_en: 'Other',               icon: 'MoreHorizontal' },
];

const BASE_LISTING = {
  departure_date: null,
  departure_time: null,
  origin: null,
  destination: null,
  is_featured: false,
  phone: null,
  is_verified: false,
  promotion_until: null,
  rejection_reason: null,
};

export const DEMO_LISTINGS: Listing[] = [
  // ── BEAUTY ──────────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-01',
    user_id: 'user-01',
    category_id: 'cat-03',
    title: 'Перукар-стиліст Олена',
    description: 'Професійні стрижки, фарбування, укладки. Досвід роботи 8 років. Працюю з усіма типами волосся. Використовую тільки преміум косметику Wella та L\'Oréal.',
    price: 150,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=400&fit=crop',
    ],
    telegram_username: 'olena_stylist',
    owner_telegram_id: 111222333,
    status: 'approved',
    rating_avg: 4.8,
    latitude: 45.6495,
    longitude: 25.5910,
    address_text: 'Str. Republicii 42, Brasov',
    languages: ['RU', 'UA'],
    districts: ['Centrul Civic', 'Centrul Istoric', 'Astra'],
    services: ['Стрижки', 'Фарбування', 'Укладки', 'Ламінування'],
    phone: '+40712345678',
    is_verified: true,
    promotion_level: 'premium',
    promotion_until: '2026-12-31T23:59:59Z',
    created_at: '2026-05-20T10:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-02b',
    user_id: 'user-02b',
    category_id: 'cat-03',
    title: 'Манікюр та педикюр — Вікторія',
    description: 'Гель-лак, нарощування нігтів, апаратний педикюр. Студія біля торгового центру AFI. Запис онлайн. Всі матеріали сертифіковані.',
    price: 120,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&h=400&fit=crop',
    ],
    telegram_username: 'vika_nails_bv',
    owner_telegram_id: 112233445,
    status: 'approved',
    rating_avg: 4.9,
    latitude: 45.6548,
    longitude: 25.6012,
    address_text: 'B-dul Saturn 3, Brasov',
    languages: ['UA', 'RU', 'RO'],
    districts: ['Astra', 'Tractorul'],
    services: ['Гель-лак', 'Нарощування', 'Педикюр', 'Дизайн нігтів'],
    phone: '+40734567890',
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-19T09:30:00Z',
  },

  // ── ACCOUNTING ──────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-02',
    user_id: 'user-02',
    category_id: 'cat-11',
    title: 'Бухгалтер Наталія — звітність в Румунії',
    description: 'Допомагаю підприємцям і фізичним особам з бухгалтерією в Румунії. Реєстрація PFA/SRL, щомісячна звітність ANAF, консультації з оподаткування.',
    price: 200,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=400&fit=crop',
    ],
    telegram_username: 'natalia_contabil',
    owner_telegram_id: 444555666,
    status: 'approved',
    rating_avg: 4.9,
    latitude: 45.6520,
    longitude: 25.5890,
    address_text: 'B-dul Eroilor 14, Brasov',
    languages: ['RU', 'UA', 'RO'],
    districts: ['Centrul Civic', 'Centrul Istoric'],
    services: ['Бухгалтерія', 'Реєстрація PFA', 'Реєстрація SRL', 'Звітність ANAF'],
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-18T09:00:00Z',
  },

  // ── EDUCATION ───────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-03',
    user_id: 'user-03',
    category_id: 'cat-09',
    title: 'Репетитор з математики — Олексій',
    description: 'Підготовка до BAC та вступу до університету. Онлайн та офлайн заняття. Досвід 10 років викладання. Гарантую результат або повернення грошей.',
    price: 80,
    currency: 'RON',
    photos: [],
    telegram_username: 'aleksey_math',
    owner_telegram_id: 777888999,
    status: 'approved',
    rating_avg: 4.6,
    latitude: 45.6480,
    longitude: 25.6000,
    address_text: 'Tractorul, Brasov',
    languages: ['RU', 'UA', 'RO', 'EN'],
    districts: ['Tractorul', 'Noua', 'Florilor'],
    services: ['Математика', 'BAC', 'Підготовка до університету', 'Онлайн'],
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-15T14:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-03b',
    user_id: 'user-03b',
    category_id: 'cat-09',
    title: 'Курси румунської мови — Іванна',
    description: 'Викладаю румунську мову для дорослих і дітей. Індивідуально та в міні-групах до 4 осіб. Підготовка до іспиту на громадянство. Рівень A1–B2.',
    price: 100,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=400&fit=crop',
    ],
    telegram_username: 'ivanna_romana',
    owner_telegram_id: 778899001,
    status: 'approved',
    rating_avg: 5.0,
    latitude: 45.6501,
    longitude: 25.5945,
    address_text: 'Str. Lungă 30, Brasov',
    languages: ['UA', 'RO'],
    districts: ['Centrul Civic', 'Centrul Istoric', 'Schei'],
    services: ['Румунська мова', 'Для дітей', 'Для дорослих', 'Громадянство'],
    phone: '+40756789012',
    is_verified: true,
    promotion_level: 'premium',
    promotion_until: '2026-10-31T23:59:59Z',
    created_at: '2026-05-17T11:00:00Z',
  },

  // ── MEDICINE ────────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-04',
    user_id: 'user-04',
    category_id: 'cat-04',
    title: 'Лікар-терапевт Марина',
    description: 'Консультації терапевта, допомога з медичними документами для резидентів. Прийом у приватній клініці та онлайн. Говорю українською та румунською.',
    price: 250,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&h=400&fit=crop',
    ],
    telegram_username: 'dr_marina_brasov',
    owner_telegram_id: 123123123,
    status: 'approved',
    rating_avg: 4.7,
    latitude: 45.6510,
    longitude: 25.5930,
    address_text: 'Str. Muresenilor 10, Brasov',
    languages: ['RU', 'UA', 'RO'],
    districts: ['Centrul Civic', 'Astra', 'Scriitorilor'],
    services: ['Терапевт', 'Медичні документи', 'Онлайн-консультація', 'Направлення до фахівців'],
    phone: '+40723456789',
    is_verified: true,
    promotion_level: 'premium',
    promotion_until: '2026-11-30T23:59:59Z',
    created_at: '2026-05-10T08:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-04b',
    user_id: 'user-04b',
    category_id: 'cat-04',
    title: 'Психолог Оксана — підтримка для переселенців',
    description: 'Індивідуальні консультації та групова терапія. Спеціалізуюсь на підтримці людей, що пережили переселення та стрес. Онлайн та офлайн в Брашові.',
    price: 180,
    currency: 'RON',
    photos: [],
    telegram_username: 'oksana_psych',
    owner_telegram_id: 124124124,
    status: 'approved',
    rating_avg: 4.8,
    latitude: null,
    longitude: null,
    address_text: 'Brasov (онлайн або зустріч)',
    languages: ['UA', 'RU'],
    districts: ['Centrul Civic', 'Tractorul', 'Noua'],
    services: ['Психологія', 'Онлайн', 'Групова терапія', 'Підтримка переселенців'],
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-14T10:00:00Z',
  },

  // ── CHILDCARE ───────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-05',
    user_id: 'user-05',
    category_id: 'cat-12',
    title: 'Няня Світлана — досвід 5 років',
    description: 'Доглядаю за дітьми від 1 до 10 років. Досвід з немовлятами. Можу забирати зі школи та дитячого садка. Є рекомендації від попередніх родин.',
    price: 40,
    currency: 'RON',
    photos: [],
    telegram_username: 'nanny_svitlana',
    owner_telegram_id: 321321321,
    status: 'approved',
    rating_avg: 5.0,
    latitude: null,
    longitude: null,
    address_text: null,
    languages: ['RU', 'UA'],
    districts: ['Tractorul', 'Noua', 'Craiter'],
    services: ['Няня', 'Немовлята', 'Школярі', 'Вивезення зі школи'],
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-12T11:00:00Z',
  },

  // ── REPAIR ──────────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-06',
    user_id: 'user-06',
    category_id: 'cat-07',
    title: 'Ремонт квартир — бригада Андрія',
    description: 'Косметичний та капітальний ремонт квартир і будинків. Плитка, шпаклювання, електрика, сантехніка. Безкоштовний виїзд на огляд. Договір, гарантія.',
    price: null,
    currency: null,
    photos: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop',
    ],
    telegram_username: 'remont_andrey',
    owner_telegram_id: 456456456,
    status: 'approved',
    rating_avg: 4.4,
    latitude: null,
    longitude: null,
    address_text: 'Brasov та передмістя',
    languages: ['RU', 'UA'],
    districts: ['Out of Town / Delivery'],
    services: ['Косметичний ремонт', 'Плитка', 'Шпаклювання', 'Електрика', 'Сантехніка'],
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-08T16:00:00Z',
  },

  // ── TRANSPORT / CARPOOLING ───────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-07',
    user_id: 'user-07',
    category_id: 'cat-02',
    title: 'Попутка Брашов → Бухарест',
    description: 'Їду в Бухарест кожну п\'ятницю. Є 3 вільних місця. Комфортний Mercedes. Розбираємо вартість бензину. Відправлення о 07:00 від вокзалу.',
    price: 50,
    currency: 'RON',
    photos: [],
    telegram_username: 'carpooling_dmytro',
    owner_telegram_id: 567567567,
    status: 'approved',
    rating_avg: 4.5,
    latitude: 45.6434,
    longitude: 25.5876,
    address_text: 'Gara Brasov (залізничний вокзал)',
    languages: ['UA', 'RU', 'RO'],
    districts: ['Centrul Civic'],
    services: ['Попутка', 'Щотижнево'],
    departure_date: '2026-05-30',
    departure_time: '07:00',
    origin: 'Brasov',
    destination: 'Bucuresti',
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-22T08:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-07b',
    user_id: 'user-07b',
    category_id: 'cat-02',
    title: 'Трансфер Брашов → Клуж-Напока',
    description: 'Комфортний трансфер до Клуж-Напоки. Відправлення за домовленістю. Toyota Corolla, кондиціонер, музика. Беру до 3-х пасажирів + багаж.',
    price: 80,
    currency: 'RON',
    photos: [],
    telegram_username: 'transfer_vasyl',
    owner_telegram_id: 568568568,
    status: 'approved',
    rating_avg: 4.7,
    latitude: 45.6434,
    longitude: 25.5876,
    address_text: 'Brasov — по домовленості',
    languages: ['UA', 'RU'],
    districts: ['Centrul Civic', 'Tractorul'],
    services: ['Трансфер', 'Клуж', 'По запиту'],
    departure_date: '2026-05-28',
    departure_time: '09:00',
    origin: 'Brasov',
    destination: 'Cluj-Napoca',
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-21T15:00:00Z',
  },

  // ── HOUSING ─────────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-08',
    user_id: 'user-08',
    category_id: 'cat-01',
    title: 'Здається 2-кімнатна квартира — Centrul Civic',
    description: 'Чиста, повністю мебльована квартира в центрі Брашова. 2 кімнати, кухня з технікою, ванна. Поряд із зупинкою. Мінімум 3 місяці. Без посередників.',
    price: 400,
    currency: 'EUR',
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop',
    ],
    telegram_username: 'apartment_ihor',
    owner_telegram_id: 678678678,
    status: 'approved',
    rating_avg: 4.6,
    latitude: 45.6488,
    longitude: 25.5925,
    address_text: 'Str. Mihai Eminescu 7, Brasov',
    languages: ['UA', 'RU', 'RO'],
    districts: ['Centrul Civic', 'Centrul Istoric'],
    services: ['Оренда', '2 кімнати', 'Мебльована', 'Без посередників'],
    phone: '+40745678901',
    is_verified: true,
    promotion_level: 'premium',
    promotion_until: '2026-09-30T23:59:59Z',
    created_at: '2026-05-16T12:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-08b',
    user_id: 'user-08b',
    category_id: 'cat-01',
    title: 'Кімната в квартирі — Tractorul',
    description: 'Здаю кімнату в 3-кімнатній квартирі. Сусіди — тихі українці. Спільна кухня та ванна. Включено: інтернет, комунальні послуги. Можна з однією дитиною.',
    price: 200,
    currency: 'EUR',
    photos: [],
    telegram_username: 'room_tractorul',
    owner_telegram_id: 679679679,
    status: 'approved',
    rating_avg: 4.2,
    latitude: 45.6605,
    longitude: 25.6080,
    address_text: 'Tractorul, Brasov',
    languages: ['UA', 'RU'],
    districts: ['Tractorul', 'Noua'],
    services: ['Кімната', 'Інтернет включений', 'Комунальні включені'],
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-13T17:00:00Z',
  },

  // ── IT SERVICES ─────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-09',
    user_id: 'user-09',
    category_id: 'cat-14',
    title: 'Розробка сайтів та магазинів — Микола',
    description: 'Створюю сайти, інтернет-магазини, лендінги. React, WordPress, Shopify. SEO-оптимізація. Підтримка та оновлення. Портфоліо на запит.',
    price: 800,
    currency: 'EUR',
    photos: [
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&h=400&fit=crop',
    ],
    telegram_username: 'mykola_dev',
    owner_telegram_id: 789789789,
    status: 'approved',
    rating_avg: 4.9,
    latitude: null,
    longitude: null,
    address_text: 'Онлайн / Brasov',
    languages: ['UA', 'EN', 'RO'],
    districts: ['Centrul Civic', 'Tractorul', 'Noua'],
    services: ['Сайти', 'Інтернет-магазини', 'React', 'WordPress', 'SEO'],
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-11T09:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-09b',
    user_id: 'user-09b',
    category_id: 'cat-14',
    title: 'Ремонт комп\'ютерів та ноутбуків',
    description: 'Діагностика та ремонт ПК, ноутбуків, планшетів. Заміна батарей, дисплеїв, клавіатур. Встановлення Windows/Linux. Виїзд додому. Ціна після діагностики.',
    price: 80,
    currency: 'RON',
    photos: [],
    telegram_username: 'pc_repair_bv',
    owner_telegram_id: 790790790,
    status: 'approved',
    rating_avg: 4.5,
    latitude: 45.6550,
    longitude: 25.6020,
    address_text: 'Astra, Brasov',
    languages: ['UA', 'RU', 'RO'],
    districts: ['Astra', 'Centrul Civic', 'Tractorul'],
    services: ['Ремонт ПК', 'Ноутбуки', 'Заміна батареї', 'Windows', 'Виїзд додому'],
    phone: '+40767890123',
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-09T13:00:00Z',
  },

  // ── LEGAL ───────────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-10',
    user_id: 'user-10',
    category_id: 'cat-10',
    title: 'Юрист — дозвіл на проживання в Румунії',
    description: 'Допомагаю з отриманням та продовженням дозволу на проживання. Підготовка документів, представлення в IGI. Супровід на всіх етапах.',
    price: 350,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&h=400&fit=crop',
    ],
    telegram_username: 'lawyer_olha',
    owner_telegram_id: 890890890,
    status: 'approved',
    rating_avg: 4.8,
    latitude: 45.6515,
    longitude: 25.5915,
    address_text: 'Str. Apollonia Hirscher 2, Brasov',
    languages: ['UA', 'RU', 'RO', 'EN'],
    districts: ['Centrul Civic', 'Centrul Istoric'],
    services: ['Дозвіл на проживання', 'Документи', 'IGI', 'Громадянство'],
    phone: '+40778901234',
    is_verified: true,
    promotion_level: 'premium',
    promotion_until: '2026-12-31T23:59:59Z',
    created_at: '2026-05-07T10:00:00Z',
  },

  // ── CLEANING ────────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-11',
    user_id: 'user-11',
    category_id: 'cat-08',
    title: 'Клінінг квартир та офісів — Галина',
    description: 'Генеральне та підтримуюче прибирання. Прибирання після ремонту. Своє обладнання та засоби. Підтверджу виконання фото до/після.',
    price: 200,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&h=400&fit=crop',
    ],
    telegram_username: 'cleaning_halyna',
    owner_telegram_id: 901901901,
    status: 'approved',
    rating_avg: 4.7,
    latitude: null,
    longitude: null,
    address_text: 'Весь Брашов',
    languages: ['UA', 'RU'],
    districts: ['Centrul Civic', 'Tractorul', 'Astra', 'Noua'],
    services: ['Генеральне прибирання', 'Підтримуюче', 'Після ремонту', 'Офіси'],
    phone: '+40789012345',
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-06T14:00:00Z',
  },

  // ── PHOTO / VIDEO ───────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-12',
    user_id: 'user-12',
    category_id: 'cat-13',
    title: 'Фотограф Тарас — портрети та репортажі',
    description: 'Фотографую сімейні та особисті портрети, весілля, корпоративи, репортажі. Обробка в течії 5 днів. Є портфоліо. Фотосесії в горах Брашова.',
    price: 500,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1471341971476-ae15ff5dd4ea?w=600&h=400&fit=crop',
    ],
    telegram_username: 'taras_photo_bv',
    owner_telegram_id: 912912912,
    status: 'approved',
    rating_avg: 5.0,
    latitude: null,
    longitude: null,
    address_text: 'Brasov та регіон',
    languages: ['UA', 'RU', 'RO', 'EN'],
    districts: ['Centrul Civic', 'Schei', 'Warthe/Noua'],
    services: ['Портрети', 'Весілля', 'Корпоративи', 'Репортаж', 'Гори'],
    is_verified: true,
    promotion_level: 'premium',
    promotion_until: '2026-11-30T23:59:59Z',
    created_at: '2026-05-05T10:00:00Z',
  },

  // ── AUTO ────────────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-13',
    user_id: 'user-13',
    category_id: 'cat-15',
    title: 'СТО — Діагностика та ремонт авто',
    description: 'Комп\'ютерна діагностика, ремонт двигуна, заміна масла та фільтрів, розвал-схождення. Офіційне СТО. Є підйомник. Говоримо українською.',
    price: 150,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1625047509252-ab38fb5c7343?w=600&h=400&fit=crop',
    ],
    telegram_username: 'sto_brasov_ua',
    owner_telegram_id: 923923923,
    status: 'approved',
    rating_avg: 4.5,
    latitude: 45.6620,
    longitude: 25.6050,
    address_text: 'Str. Zizinului 110, Brasov',
    languages: ['UA', 'RU', 'RO'],
    districts: ['Tractorul', 'Noua'],
    services: ['Діагностика', 'Ремонт двигуна', 'Заміна масла', 'Розвал-схождення'],
    phone: '+40790123456',
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-04T08:00:00Z',
  },

  // ── DELIVERY ────────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-14',
    user_id: 'user-14',
    category_id: 'cat-16',
    title: 'Доставка передач Брашов ↔ Україна',
    description: 'Організовую доставку посилок та передач між Брашовим і Львовом, Києвом, Одесою. Відправлення двічі на місяць. Ліки, одяг, продукти — все беру.',
    price: 30,
    currency: 'EUR',
    photos: [],
    telegram_username: 'delivery_ua_ro',
    owner_telegram_id: 934934934,
    status: 'approved',
    rating_avg: 4.6,
    latitude: null,
    longitude: null,
    address_text: 'Brasov ↔ Україна',
    languages: ['UA', 'RU'],
    districts: ['Out of Town / Delivery'],
    services: ['Посилки', 'Ліки', 'Продукти', 'Двічі на місяць', 'Львів', 'Київ'],
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-03T10:00:00Z',
  },

  // ── PETS ────────────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-15',
    user_id: 'user-15',
    category_id: 'cat-18',
    title: 'Зоосалон — стрижка та догляд за домашніми тваринами',
    description: 'Стрижка, купання, чистка вух та зубів для собак і котів. Досвід 6 років. Є мобільний зоосалон — приїжджаю додому. Прайс залежить від породи.',
    price: 100,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop',
    ],
    telegram_username: 'petcare_brasov',
    owner_telegram_id: 945945945,
    status: 'approved',
    rating_avg: 4.8,
    latitude: 45.6490,
    longitude: 25.5950,
    address_text: 'Str. Harmanului 20, Brasov',
    languages: ['UA', 'RU', 'RO'],
    districts: ['Astra', 'Centrul Civic'],
    services: ['Стрижка', 'Купання', 'Виїзд додому', 'Собаки', 'Коти'],
    phone: '+40701234567',
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-02T11:00:00Z',
  },

  // ── VETERINARY ──────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-15b',
    user_id: 'user-15b',
    category_id: 'cat-05',
    title: 'Ветеринар Богдан — прийом вдома та в клініці',
    description: 'Ветеринарна допомога для домашніх тварин. Вакцинація, паразитологія, лікування. Виїзд додому в межах Брашова. Нічні виклики за домовленістю.',
    price: 150,
    currency: 'RON',
    photos: [],
    telegram_username: 'vet_bohdan_bv',
    owner_telegram_id: 946946946,
    status: 'approved',
    rating_avg: 4.9,
    latitude: 45.6530,
    longitude: 25.5970,
    address_text: 'Centrul Civic, Brasov',
    languages: ['UA', 'RU', 'RO'],
    districts: ['Centrul Civic', 'Astra', 'Scriitorilor'],
    services: ['Ветеринар', 'Вакцинація', 'Виїзд додому', 'Нічний виклик'],
    phone: '+40712345670',
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-01T09:00:00Z',
  },

  // ── MARKETPLACE ─────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-16',
    user_id: 'user-16',
    category_id: 'cat-19',
    title: 'Продам дитячий велосипед — майже новий',
    description: 'Велосипед для дитини 5–8 років, колеса 20". Куплений 6 місяців тому, їздили 10 разів. Є захисне спорядження у подарунок. Стан відмінний.',
    price: 150,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=600&h=400&fit=crop',
    ],
    telegram_username: 'bike_sell_bv',
    owner_telegram_id: 956956956,
    status: 'approved',
    rating_avg: 0,
    latitude: null,
    longitude: null,
    address_text: 'Tractorul, Brasov',
    languages: ['UA'],
    districts: ['Tractorul'],
    services: ['Велосипед', 'Дитячий', 'Продаж'],
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-23T16:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-16b',
    user_id: 'user-16b',
    category_id: 'cat-19',
    title: 'Куплю / обміняю зимову гуму — R16',
    description: 'Шукаю зимову резину розміру 205/55 R16 або 215/55 R16 у гарному стані. Можу запропонувати обмін або готівку. Пишіть із фото та ціною.',
    price: 400,
    currency: 'RON',
    photos: [],
    telegram_username: 'tires_wanted',
    owner_telegram_id: 957957957,
    status: 'approved',
    rating_avg: 0,
    latitude: null,
    longitude: null,
    address_text: 'Brasov',
    languages: ['UA', 'RU'],
    districts: ['Centrul Civic', 'Tractorul', 'Astra'],
    services: ['Куплю', 'Обмін', 'Шини R16'],
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-22T14:00:00Z',
  },

  // ── RESTAURANTS ─────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-17',
    user_id: 'user-17',
    category_id: 'cat-06',
    title: 'Домашня їжа на замовлення — Людмила',
    description: 'Готую домашні страви: борщ, вареники, голубці, пироги. Доставка по Брашову або самовивіз. Мінімальне замовлення 100 RON. Замовляйте напередодні.',
    price: 35,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&h=400&fit=crop',
    ],
    telegram_username: 'homefood_lyudmyla',
    owner_telegram_id: 967967967,
    status: 'approved',
    rating_avg: 4.9,
    latitude: null,
    longitude: null,
    address_text: 'Brasov — доставка або самовивіз',
    languages: ['UA', 'RU'],
    districts: ['Centrul Civic', 'Tractorul', 'Noua', 'Astra'],
    services: ['Борщ', 'Вареники', 'Голубці', 'Пироги', 'Доставка'],
    phone: '+40723456780',
    is_verified: true,
    promotion_level: 'premium',
    promotion_until: '2026-10-31T23:59:59Z',
    created_at: '2026-04-28T10:00:00Z',
  },

  // ── EVENTS ──────────────────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-18',
    user_id: 'user-18',
    category_id: 'cat-17',
    title: 'Організація дитячих свят та анімація',
    description: 'Аніматори, клоуни, фокусники для дитячих днів народження та свят. Від 2 годин. Власний реквізит та костюми. Можна в парку або вдома.',
    price: 300,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&h=400&fit=crop',
    ],
    telegram_username: 'party_kids_bv',
    owner_telegram_id: 978978978,
    status: 'approved',
    rating_avg: 4.7,
    latitude: null,
    longitude: null,
    address_text: 'Brasov та передмістя',
    languages: ['UA', 'RU', 'RO'],
    districts: ['Centrul Civic', 'Tractorul', 'Astra'],
    services: ['Аніматори', 'Клоун', 'Фокусник', 'Дні народження'],
    phone: '+40734567891',
    is_verified: false,
    promotion_level: 'basic',
    created_at: '2026-04-25T12:00:00Z',
  },

  // ── SCAM (blacklisted) ──────────────────────────────────────────────────
  {
    ...BASE_LISTING,
    id: 'lst-scam',
    user_id: 'user-scam',
    category_id: 'cat-01',
    title: 'Оренда квартири — дешево центр',
    description: 'Здається квартира в центрі. Пишіть терміново — є охочих багато.',
    price: 200,
    currency: 'EUR',
    photos: [],
    telegram_username: 'scam_rental',
    owner_telegram_id: 999888777,
    status: 'approved',
    rating_avg: 0,
    latitude: null,
    longitude: null,
    address_text: null,
    languages: ['RU'],
    districts: ['Centrul Civic'],
    services: [],
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-01T00:00:00Z',
  },
];

export const DEMO_BLACKLIST: BlacklistEntry[] = [
  {
    id: 'bl-01',
    telegram_id: 999888777,
    reason_uk: 'Шахрайство з орендою — бере передоплату та зникає',
    reason_ro: 'Frauda cu chiria — ia avans si dispare',
    reason_en: 'Rental scam — takes deposit and disappears',
    proof_url: null,
    added_at: '2026-05-03T10:00:00Z',
  },
];
