import type { Category, Listing, BlacklistEntry } from '../types';

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-01', slug: 'housing',    name_uk: 'Нерухомість',        name_ro: 'Imobiliare',          name_en: 'Real Estate',         icon: 'Home' },
  { id: 'cat-02', slug: 'transport',  name_uk: 'Перевезення',         name_ro: 'Transport',           name_en: 'Transportation',      icon: 'Car' },
  { id: 'cat-03', slug: 'beauty',     name_uk: "Краса та здоров'я",  name_ro: 'Frumusete',           name_en: 'Beauty & Health',     icon: 'Sparkles' },
  { id: 'cat-04', slug: 'medicine',   name_uk: 'Медицина',            name_ro: 'Medicina',            name_en: 'Medicine',            icon: 'Heart' },
  { id: 'cat-05', slug: 'veterinary', name_uk: 'Ветеринарія',         name_ro: 'Veterinar',           name_en: 'Veterinary',          icon: 'Dog' },
  { id: 'cat-06', slug: 'restaurants',name_uk: 'Ресторани і кафе',    name_ro: 'Restaurante',         name_en: 'Restaurants & Cafes', icon: 'UtensilsCrossed' },
  { id: 'cat-07', slug: 'repair',     name_uk: 'Ремонт і будівництво',name_ro: 'Reparatii',           name_en: 'Repair & Construction',icon: 'Wrench' },
  { id: 'cat-08', slug: 'cleaning',   name_uk: 'Клінінг',             name_ro: 'Curatenie',           name_en: 'Cleaning',            icon: 'SprayCan' },
  { id: 'cat-09', slug: 'education',  name_uk: 'Освіта та курси',     name_ro: 'Educatie',            name_en: 'Education & Courses', icon: 'GraduationCap' },
  { id: 'cat-10', slug: 'legal',      name_uk: 'Юридичні послуги',    name_ro: 'Juridice',            name_en: 'Legal Services',      icon: 'Scale' },
  { id: 'cat-11', slug: 'accounting', name_uk: 'Бухгалтерія',         name_ro: 'Contabilitate',       name_en: 'Accounting',          icon: 'Calculator' },
  { id: 'cat-12', slug: 'childcare',  name_uk: 'Дитячі послуги',      name_ro: 'Copii',               name_en: 'Childcare',           icon: 'Baby' },
  { id: 'cat-13', slug: 'photo_video',name_uk: 'Фото та відео',       name_ro: 'Foto/Video',          name_en: 'Photo & Video',       icon: 'Camera' },
  { id: 'cat-14', slug: 'it_services',name_uk: 'IT послуги',          name_ro: 'IT',                  name_en: 'IT Services',         icon: 'Monitor' },
  { id: 'cat-15', slug: 'auto',       name_uk: 'Автосервіс',          name_ro: 'Auto',                name_en: 'Auto Service',        icon: 'CarFront' },
  { id: 'cat-16', slug: 'delivery',   name_uk: 'Доставка',            name_ro: 'Livrare',             name_en: 'Delivery',            icon: 'Package' },
  { id: 'cat-17', slug: 'events',     name_uk: 'Івенти',              name_ro: 'Evenimente',          name_en: 'Events',              icon: 'PartyPopper' },
  { id: 'cat-18', slug: 'pets',       name_uk: 'Тварини',             name_ro: 'Animale',             name_en: 'Pets',                icon: 'PawPrint' },
  { id: 'cat-19', slug: 'marketplace',name_uk: 'Купівля / Продаж',    name_ro: 'Cumparare/Vanzare',   name_en: 'Buy / Sell',          icon: 'ShoppingBag' },
  { id: 'cat-20', slug: 'other',      name_uk: 'Інше',                name_ro: 'Altele',              name_en: 'Other',               icon: 'MoreHorizontal' },
];

const BASE_LISTING = {
  departure_date: null,
  departure_time: null,
  origin: null,
  destination: null,
  is_featured: false,
  phone: null,
  is_verified: false,
  promotion_until: null,
  rejection_reason: null,
};

export const DEMO_LISTINGS: Listing[] = [
  {
    ...BASE_LISTING,
    id: 'lst-01',
    user_id: 'user-01',
    category_id: 'cat-03',
    title: 'Перукар-стиліст Олена',
    description: 'Професійні стрижки, фарбування, укладки. Досвід роботи 8 років. Працюю з усіма типами волосся. Використовую тільки преміум косметику.',
    price: 150,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=400&fit=crop',
    ],
    telegram_username: 'olena_stylist',
    owner_telegram_id: 111222333,
    status: 'approved',
    rating_avg: 4.8,
    latitude: 45.6495,
    longitude: 25.5910,
    address_text: 'Str. Republicii 42, Brasov',
    languages: ['RU', 'UA'],
    districts: ['Centrul Civic', 'Centrul Istoric', 'Astra'],
    services: ['Стрижки', 'Фарбування', 'Укладки'],
    phone: '+40712345678',
    is_verified: true,
    promotion_level: 'premium',
    promotion_until: '2026-12-31T23:59:59Z',
    created_at: '2026-05-20T10:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-02',
    user_id: 'user-02',
    category_id: 'cat-11',
    title: 'Бухгалтер Наталія — звітність в Румунії',
    description: 'Допомагаю підприємцям і фізичним особам з бухгалтерією в Румунії. Реєстрація PFA/SRL, щомісячна звітність, консультації.',
    price: 200,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=400&fit=crop',
    ],
    telegram_username: 'natalia_contabil',
    owner_telegram_id: 444555666,
    status: 'approved',
    rating_avg: 4.9,
    latitude: 45.6520,
    longitude: 25.5890,
    address_text: 'B-dul Eroilor 14, Brasov',
    languages: ['RU', 'UA', 'RO'],
    districts: ['Centrul Civic', 'Centrul Istoric'],
    services: ['Бухгалтерія', 'Реєстрація PFA', 'Реєстрація SRL', 'Звітність ANAF'],
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-18T09:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-03',
    user_id: 'user-03',
    category_id: 'cat-09',
    title: 'Репетитор з математики — Олексій',
    description: 'Підготовка до BAC та вступу до університету. Онлайн та офлайн заняття. Досвід 10 років.',
    price: 80,
    currency: 'RON',
    photos: [],
    telegram_username: 'aleksey_math',
    owner_telegram_id: 777888999,
    status: 'approved',
    rating_avg: 4.6,
    latitude: 45.6480,
    longitude: 25.6000,
    address_text: 'Tractorul, Brasov',
    languages: ['RU', 'UA', 'RO', 'EN'],
    districts: ['Tractorul', 'Noua', 'Florilor'],
    services: ['Математика', 'BAC', 'Підготовка до університету', 'Онлайн'],
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-15T14:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-04',
    user_id: 'user-04',
    category_id: 'cat-04',
    title: 'Лікар-терапевт Марина',
    description: 'Консультації терапевта, допомога з медичними документами для резидентів. Прийом в приватній клініці та онлайн.',
    price: 250,
    currency: 'RON',
    photos: [
      'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&h=400&fit=crop',
    ],
    telegram_username: 'dr_marina_brasov',
    owner_telegram_id: 123123123,
    status: 'approved',
    rating_avg: 4.7,
    latitude: 45.6510,
    longitude: 25.5930,
    address_text: 'Str. Muresenilor 10, Brasov',
    languages: ['RU', 'UA', 'RO'],
    districts: ['Centrul Civic', 'Astra', 'Scriitorilor'],
    services: ['Терапевт', 'Медичні документи', 'Онлайн-консультація'],
    phone: '+40723456789',
    is_verified: true,
    promotion_level: 'premium',
    promotion_until: '2026-11-30T23:59:59Z',
    created_at: '2026-05-10T08:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-05',
    user_id: 'user-05',
    category_id: 'cat-12',
    title: 'Няня Світлана — досвід 5 років',
    description: 'Доглядаю за дітьми від 1 до 10 років. Досвід з немовлятами. Можу забирати зі школи та садка. Район Tractorul та Noua.',
    price: 40,
    currency: 'RON',
    photos: [],
    telegram_username: 'nanny_svitlana',
    owner_telegram_id: 321321321,
    status: 'approved',
    rating_avg: 5.0,
    latitude: null,
    longitude: null,
    address_text: null,
    languages: ['RU', 'UA'],
    districts: ['Tractorul', 'Noua', 'Craiter'],
    services: ['Няня', 'Немовлята', 'Школярі', 'Вивезення зі школи'],
    is_verified: true,
    promotion_level: 'basic',
    created_at: '2026-05-12T11:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-06',
    user_id: 'user-06',
    category_id: 'cat-07',
    title: 'Ремонт квартир — бригада Андрія',
    description: 'Косметичний та капітальний ремонт квартир і будинків. Плитка, шпаклювання, електрика, сантехніка. Безкоштовний виїзд на огляд.',
    price: null,
    currency: null,
    photos: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop',
    ],
    telegram_username: 'remont_andrey',
    owner_telegram_id: 456456456,
    status: 'approved',
    rating_avg: 4.4,
    latitude: null,
    longitude: null,
    address_text: 'Brasov та передмістя',
    languages: ['RU', 'UA'],
    districts: ['Out of Town / Delivery'],
    services: ['Косметичний ремонт', 'Плитка', 'Шпаклювання', 'Електрика', 'Сантехніка'],
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-08T16:00:00Z',
  },
  {
    ...BASE_LISTING,
    id: 'lst-scam',
    user_id: 'user-scam',
    category_id: 'cat-01',
    title: 'Оренда квартири — дешево центр',
    description: 'Здається квартира в центрі. Пишіть терміново — є охочих багато.',
    price: 200,
    currency: 'EUR',
    photos: [],
    telegram_username: 'scam_rental',
    owner_telegram_id: 999888777,
    status: 'approved',
    rating_avg: 0,
    latitude: null,
    longitude: null,
    address_text: null,
    languages: ['RU'],
    districts: ['Centrul Civic'],
    services: [],
    is_verified: false,
    promotion_level: 'free',
    created_at: '2026-05-01T00:00:00Z',
  },
];

export const DEMO_BLACKLIST: BlacklistEntry[] = [
  {
    id: 'bl-01',
    telegram_id: 999888777,
    reason_uk: 'Шахрайство з орендою — бере передоплату та зникає',
    reason_ro: 'Frauda cu chiria — ia avans si dispare',
    reason_en: 'Rental scam — takes deposit and disappears',
    proof_url: null,
    added_at: '2026-05-03T10:00:00Z',
  },
];
